// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrty5I1qL8IRNpwtrWdCE81g1gvaqkQ74',
    appId: '1:876115920494:web:7437fac78454c7c479c87f',
    messagingSenderId: '876115920494',
    projectId: 'emotional-support-app-ed753',
    authDomain: 'emotional-support-app-ed753.firebaseapp.com',
    storageBucket: 'emotional-support-app-ed753.appspot.com',
    measurementId: 'G-1ZPE4RNX37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6IgkcxACJmP7YB8Ep2M5uwokqVrv1TJA',
    appId: '1:876115920494:android:3954760bc287edfd79c87f',
    messagingSenderId: '876115920494',
    projectId: 'emotional-support-app-ed753',
    storageBucket: 'emotional-support-app-ed753.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByfvnVxtiGElLYjdUrt__N9_CtukLzRqk',
    appId: '1:876115920494:ios:71a2005950a6e1aa79c87f',
    messagingSenderId: '876115920494',
    projectId: 'emotional-support-app-ed753',
    storageBucket: 'emotional-support-app-ed753.appspot.com',
    iosBundleId: 'com.example.emotionsSupportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByfvnVxtiGElLYjdUrt__N9_CtukLzRqk',
    appId: '1:876115920494:ios:71a2005950a6e1aa79c87f',
    messagingSenderId: '876115920494',
    projectId: 'emotional-support-app-ed753',
    storageBucket: 'emotional-support-app-ed753.appspot.com',
    iosBundleId: 'com.example.emotionsSupportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrty5I1qL8IRNpwtrWdCE81g1gvaqkQ74',
    appId: '1:876115920494:web:4e193782dce3df8979c87f',
    messagingSenderId: '876115920494',
    projectId: 'emotional-support-app-ed753',
    authDomain: 'emotional-support-app-ed753.firebaseapp.com',
    storageBucket: 'emotional-support-app-ed753.appspot.com',
    measurementId: 'G-XYBL00ED48',
  );
}
